### ISSUE TITLE
你好，文件夹可以生成，文件却不能生成

### ISSUE THREAD

**Issue by swliu920322** [ianva/baya#1]
报错fs.js:110
    throw new TypeError('"callback" argument must be a function');
    ^

TypeError: "callback" argument must be a function
at makeCallback (fs.js:110:11)
    at Object.fs.open (fs.js:564:18)
    at createItem (/Users/swliu/.nvm/versions/node/v7.10.0/lib/node_modules/baya/lib/baya.js:57:16)
    at /Users/swliu/.nvm/versions/node/v7.10.0/lib/node_modules/baya/lib/baya.js:100:13
    at Array.forEach (native)
    at Object.exports.generate (/Users/swliu/.nvm/versions/node/v7.10.0/lib/node_modules/baya/lib/baya.js:91:14)
    at Object.<anonymous> (/Users/swliu/.nvm/versions/node/v7.10.0/lib/node_modules/baya/bin/baya:31:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by ianva** [comment]
项目太久了，很多库的版本可能和现在的 node.js 版本存在兼容问题，稍后会解决下
